// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendeTuAutoYa.Api.Data;

#nullable disable

namespace VendeTuAutoYa.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104220616_InitialCreateSQLite")]
    partial class InitialCreateSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("VendeTuAutoYa.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 4, 22, 6, 15, 175, DateTimeKind.Utc).AddTicks(2507),
                            Email = "vendedor@vendetuautoya.com",
                            Name = "Vendedor Demo",
                            PasswordHash = "$2a$11$/9XAbCBn5yscn93E.LaDu.Ms1DTjw3uiki0EBAJy3scMQnLKKTjl.",
                            Phone = "+1234567890",
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 11, 4, 22, 6, 15, 175, DateTimeKind.Utc).AddTicks(3353)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 4, 22, 6, 15, 406, DateTimeKind.Utc).AddTicks(9065),
                            Email = "concesionario@vendetuautoya.com",
                            MembershipJson = "{\"Status\":0,\"ExpirationDate\":null,\"LastPaymentDate\":null,\"AutoRenew\":false}",
                            Name = "Concesionario Demo",
                            PasswordHash = "$2a$11$k1UASlxJmadWyjVG2pEuWu2B9TnXMSlARFT2DHT72xjifY1P1tMk2",
                            Phone = "+1234567891",
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 11, 4, 22, 6, 15, 406, DateTimeKind.Utc).AddTicks(9068)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 4, 22, 6, 15, 569, DateTimeKind.Utc).AddTicks(7303),
                            Email = "administrador@vendetuautoya.com",
                            Name = "Administrador Sistema",
                            PasswordHash = "$2a$11$NDRNptqjhcD5BIFAW0RsX.iqwowFEUsFfAQlWWeU0fzjiy6LQz6tS",
                            Phone = "+1234567892",
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 11, 4, 22, 6, 15, 569, DateTimeKind.Utc).AddTicks(7310)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 4, 22, 6, 15, 824, DateTimeKind.Utc).AddTicks(1860),
                            Email = "inversor@vendetuautoya.com",
                            Name = "Inversor Demo",
                            PasswordHash = "$2a$11$evAYvftebTI1y2ms5FXZMe9yUYZswLl9jfeyTXcTpJ9U4n1QW0pcK",
                            Phone = "+1234567893",
                            Type = 3,
                            UpdatedAt = new DateTime(2025, 11, 4, 22, 6, 15, 824, DateTimeKind.Utc).AddTicks(1865)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
